Merge 1st lab
Akiiino/Ask-Me-Anything pull request #1
Opened 2016-11-21 16:20 UTC by Akiiino

2016-11-22 10:23 UTC, mryab requested changes

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +cluster_split_figure = plt.figure(figsize=(12, 8))
Чтобы не писать везде figsize, можно добавить в начало кода следующую строчку:
matplotlib.rcParams['figure.figsize'] = '12,8'

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +cluster_split_figure.show()
В ноутбуке не отображается куча графиков из начала. 
%matplotlib inline или %matplotlib notebook должны поправить ситуацию

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +    return np.array(interm_sequence)
Можно сразу np.array сделать

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +    np.multiply(np.random.random_sample(2), np.array([20, 25]))-np.array([5, 15])  # Get random point in plotted area
Можно просто перемножить

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +    return 1/labels.size*sum((points[i].dot(candidate_vector)-labels[i])**2 for i in range(labels.size))
Сложно. Почему нельзя просто перемножить points*candidate_vector, вычесть y  и возвести в квадрат, а потом взять np.mean?

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +                (points[i].dot(candidate_vector)-labels[i]).item()*points.item((i, j))
А для одномерного объекта точно нужно вызывать .item()?

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +print(split_vector_exact[:,0])
Он же тоже одномерный по идее, зачем такие сложности?

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +    return (sum(np.sign(x.dot(classifier)) == np.sign(y) for x, y in zip(test_set, test_labels)) / train_set.shape[0]).item()
.item() вроде опять не нужен

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +times = []
Или тоже закомментить можно, или всё целиком удалить

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +def adam(grad, points, labels, learning_rate, decay_first, decay_second, batch_size, passes, start_point):
Такой вопрос: а что если мы захотим оптимизировать градиентным спуском обычную функцию, а не задающуюся выборками параметров и классов? Вроде как все наши оптимизации будут справедливы, но реализация, принимающая эти два параметра, не прокатит

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +def loss_square(margin):
PEP8: Surround top-level function and class definitions with two blank lines.

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +def func_grad(x):
Surround top-level function and class definitions with two blank lines.

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +    for iter in range(steps):
Можно перепутать с функцией iter (даже github подсвечивает!)

2016-11-22 10:23 UTC, mryab commented on Labs/Lab 1/Lab 1.py
> +    G = np.zeros((points.shape[1], points.shape[1]))
Дальше в функции не используется

2016-11-22 16:27 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +                (points[i].dot(candidate_vector)-labels[i]).item()*points.item((i, j))
Поведение массива из одного элемента и int'а могут отличаться, да. Например:

```
>>> b = np.array([1])
>>> b[0]
1
>>> b[0].item()
1
>>> c = np.array([5])
>>> np.array([b,c])
array([[1],
       [5]])
>>> np.array([1,5])
array([1, 5])
```

2016-11-22 17:52 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +print(split_vector_exact[:,0])
Чтобы вывести их в одном формате. `split_vector_exact` получается вектором-столбцом, а `split_vector_grad` --- строкой.

2016-11-22 17:53 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +    return (sum(np.sign(x.dot(classifier)) == np.sign(y) for x, y in zip(test_set, test_labels)) / train_set.shape[0]).item()
Опять же; я хочу получить число, а не np.array с одним элементом.

2016-11-22 22:28 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +def adam(grad, points, labels, learning_rate, decay_first, decay_second, batch_size, passes, start_point):
Тогда надо ещё и `batch_size` и `passes` выкидывать, а там уж и отдельную реализацию проще написать, благо не очень много правок. А эта работает по принципу стохастического градиентного спуска, и как его реализовывать без множеств элементов, которые мы пачками обрабатываем, я не знаю.

2016-11-22 22:33 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +    return 1/labels.size*sum((points[i].dot(candidate_vector)-labels[i])**2 for i in range(labels.size))
Потому что так видно и понятно, что происходит, потому как получается довольно по определению, а на производительность влияет несильно, вроде бы

2016-11-23 00:51 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +cluster_split_figure.show()
? Не вижу проблемы. Нужный backend включён, у меня всё отображается

2016-11-23 10:30 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +    G = np.zeros((points.shape[1], points.shape[1]))
Fixed

2016-11-23 10:30 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +times = []
Раскомментировал и построил график

2016-11-23 10:30 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +    np.multiply(np.random.random_sample(2), np.array([20, 25]))-np.array([5, 15])  # Get random point in plotted area
Fixed

2016-11-23 10:30 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +    return np.array(interm_sequence)
Fixed

2016-11-23 10:30 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +    for iter in range(steps):
Fixed

2016-11-23 10:30 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +def func_grad(x):
Fixed

2016-11-23 10:30 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +def loss_square(margin):
Fixed

2016-11-23 10:30 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +cluster_split_figure = plt.figure(figsize=(12, 8))
Fixed

2016-11-23 16:39 UTC, mryab approved these changes

2016-12-12 15:29 UTC, merged

2017-01-20 22:25 UTC, dasimagin reviewed
Используй более простые конструкции, а то эти вложенный for, map, list невозможно читать.

не бойся все выделять в функции очень много кода и copy+paste

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +    def __init__(self, x, y, spread):
Думаю, ты хотел сказать *vairance*

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +NORM = 50                                     # NORM helps make all features ~same magnitude. Otherwise
Вот с  NORM, кажется, что какой-то обман :) очевидно ж что средние значения у кластеров разные, как ты их "магнитуду" одной константной уровняешь, ну или я что-то не так понял :(

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +points_to_split = np.concatenate([            # Join the data matrices for all clusters
Слишком сложно, класса то всего два, можно и без циклов )

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +split_vector_exact = np.linalg.inv(points_to_split.T.dot(points_to_split)).dot(points_to_split.T).dot(true_labels)
Транспонирование можно сделать один раз :)

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +splitting_line_y = np.array((-split_vector_exact[0]*NORM - split_vector_exact[1]*x_points)/split_vector_exact[2])
Круто, что все расписал, а как строить прямую, если w_2 = 0? :(

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +#     w \approx (M_{m\times n} \times M_{n\times m})^{-1}\times M_{m \times N} \times M_{N \times 1}
Почему это approx? Это точное решение задачи минимизации!

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +# Распишем произведения и их сложности:
Ты перемножаешь матрицы в другом порядке, а это может повлиять на сложность ;) + кто-то забыл посчитать транспонирование, которые ты на самом деле ты тоже делаешь ) хотя понятно, что можно сделать так, чтобы оно стоили O(1), но все же :)

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +def loss_svm (margin):
hinge_loss

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +    interm_sequence = np.array(start_point)
Проще не париться и складывать в list, а уже потом создать array.

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +    for i in range(steps):
тут лучше бы использовать какой-нибудь критерий остановки другой, а не фиксировать количество итераций. К примеру, когда значение шага меньше эпсилон. Или изменение функции меньше эпсилон.

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +def logistic_loss_grad(w, points, labels):
тут ж можно было просто поокординатное перемножение векторов сделать, а не писать двойной цикл, работал бы гораздо быстрее! Я устал ждать :(

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +def logistic_loss_grad(w, points, labels):
НУ и чуть поразборчивее лучше писать:

```python
def logistic_loss(w, points, labels):
    result = sum(
        np.log(1 + np.exp(-label * (w.dot(point)))) for point, label in zip(points, labels)
    )
    return result / labels.size

def logistic_loss_grad(w, points, labels):
    result = sum(
        -label / (1 + np.exp(label * (w.dot(point)))) * point for point, label in zip(points, labels)
    )
    return result / labels.size

```

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +                points[j*batch_size:min((j+1)*batch_size, points.shape[0])],
вычисление индексов лучше вынести, а то сложно получает + дважды одну и ту же работу делаем.

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +    return (sum(np.sign(x.dot(classifier)) == np.sign(y) for x, y in zip(test_set, test_labels)) / train_set.shape[0]).item()
очень сложно

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +train_set[:,0] = 1
Зачем?

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +test_set[:,0] = 1
Зачем?

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +train_labels = np.concatenate([-1*np.ones((zeroes_train.shape[0], 1)), np.ones((ones_train.shape[0], 1))])
Можно просто минус поставить.

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +    batch_num = points.shape[0] // batch_size + 1
Зачем нужен +1?

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +        1e-7,
не слишком мало?

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +    return (sum(np.sign(x.dot(classifier)) == np.sign(y) for x, y in zip(test_set, test_labels)) / train_set.shape[0]).item()
А почему делим на размер обучающей выборки?

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +ones = data[data[:,0]==1]
Надо мыло случайно "замешать" обучающую выборку, чтобы плавнее училось. А то сначала 1, а потом 0.

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +smooth_plot.plot(
Я предполагал, что данные буду замешаны и тут были бы такие большие осцилляции для гамма = 0 )

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +        adaptive_classifier
stochastic_classifier?

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +        adaptive_classifier
Долго думал, почему графики такие странные. Ты обучение  loss задушил слишком маленьким рейтом, хоть качество при этом неплохое у тебя было.

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +def adadelta(grad, points, labels, gamma, batch_size, passes, start_point):
Если напечатать веса, то оне не меняются от итерации к итерации :)

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +    1e-8,
Опять придушил обучение.

2017-01-20 22:25 UTC, dasimagin commented on Labs/Lab 1/Lab 1.py
> +    0.999,
Перебор :)

2017-01-24 13:42 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +NORM = 50                                     # NORM helps make all features ~same magnitude. Otherwise
Это не для точек в кластерах; это для первой фичи, той, которая для вычисления константы используется. Без `NORM` получается, что значения координат значительно больше значений в первом элементе, и вектор гораздо медленнее сходится по первому элементу, что приводит к тому, что прямая строится под правильным углом, но сдвинута.

2017-01-24 13:43 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +points_to_split = np.concatenate([            # Join the data matrices for all clusters
Справедливо, зато обобщается легко, если вдруг захочется

2017-01-24 13:45 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +split_vector_exact = np.linalg.inv(points_to_split.T.dot(points_to_split)).dot(points_to_split.T).dot(true_labels)
Но ведь это всё равно константная операция, какая разница?

2017-01-26 12:28 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +#     w \approx (M_{m\times n} \times M_{n\times m})^{-1}\times M_{m \times N} \times M_{N \times 1}
Наверное, лучше было `\sim` поставить. Это же не сама формула, это только про размерности матриц, поэтому и не равенство.

2017-01-26 12:28 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +# Распишем произведения и их сложности:
Транспонирование в `numpy` константное, а про порядок и правда --- скобку не в том месте закрыл, похоже...

2017-01-26 12:29 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +    interm_sequence = np.array(start_point)
Максим несколькими комментариями выше говорил обратное --- у меня изначально списки и были.

2017-01-26 12:29 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +train_set[:,0] = 1
Чтобы `bias` найти; иначе же разделяющая гиперплоскость через 0 проходит, что нам не всегда даёт хороший результат.

2017-01-26 12:29 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +test_set[:,0] = 1
Аналогично прошлому.

2017-01-26 12:29 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +train_labels = np.concatenate([-1*np.ones((zeroes_train.shape[0], 1)), np.ones((ones_train.shape[0], 1))])
Можно, но какая разница?

2017-01-26 12:29 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +    batch_num = points.shape[0] // batch_size + 1
Иначе мы теряем вплоть до `batch_size-1` последних объектов; например, 100 объектов с `batch_size = 51` даст нам только один батч, что не очень хорошо

2017-01-26 12:29 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +                points[j*batch_size:min((j+1)*batch_size, points.shape[0])],
До меня это дошло только ближе к концу, забыл поправить.

2017-01-26 12:31 UTC, Akiiino commented on Labs/Lab 1/Lab 1.py
> +    return (sum(np.sign(x.dot(classifier)) == np.sign(y) for x, y in zip(test_set, test_labels)) / train_set.shape[0]).item()
Потому что стоило сменить название функции; это всё же качество распознавания, а не количество, да.